let Jobs = [
  {
    title: "Apothecary",
    building: "shop",
    names: ["Ailments", "Ointments", "Potions", "Medicines", "Pharmacy"],
  },{
    title: "Artist",
    building: "gallery",
    names: ["Gallery","Art Supplies","Art Goods","Artist"],
  },
  
  "Baker",
  "Barber",
  "Blacksmith",
  "Butcher",
  "Farmer",
  "Librarian",
  "Cleric",
  "Carpenter",
  "Candlemaker",
  "Cook",
  "Gardener",
  "Herbalist",
  "Messenger",
  "Guard",
  "Painter",
  "Physician",
  "Potter",
  "Scribe",
  "Shoemaker",
  "Spinster",
  "Shopkeeper",
]
